let stateList = [
    {value: 'al', label: 'Alabama'},
    {value: 'ak', label: 'Alaska'},
    {value: 'az', label: 'Arizona'},
    {value: 'ar', label: 'Arkansas'},
    {value: 'ca', label: 'California'},
    {value: 'ct', label: 'Connecticut'},
    {value: 'de', label: 'Delaware'},
    {value: 'fl', label: 'Florida'},
    {value: 'ga', label: 'Georgia'},
    {value: 'hi', label: 'Hawaii'},
    {value: 'id', label: 'Idaho'},
    {value: 'il', label: 'Illinois'},
    {value: 'in', label: 'Indiana'},
    {value: 'ia', label: 'Iowa'},
    {value: 'ks', label: 'Kansas'},
    {value: 'ky', label: 'Kentucky'},
    {value: 'la', label: 'Louisana'},
    {value: 'me', label: 'Maine'},
    {value: 'md', label: 'Maryland'},
    {value: 'ma', label: 'Massachusetts'},
    {value: 'mi', label: 'Michigan'},
    {value: 'mn', label: 'Minnesota'},
    {value: 'ms', label: 'Mississippi'},
    {value: 'mo', label: 'Missouri'},
    {value: 'mt', label: 'Montana'},
]

export default stateList;